export const ENUM_TURNO = {
  MAÑANA: 'MAÑANA',
  TARDE: 'TARDE',
};

export const ENUM_ESTADO_TURNO = {
  ABIERTO: 'ABIERTO',
  CERRADO: 'CERRADO',
};

export const ENUM_TIPO_MOVIMIENTO = {
  INGRESO: 'INGRESO',
  EGRESO: 'EGRESO',
};

export const ENUM_CATEGORIA = {
  VENTA: 'VENTA',
  PROVEEDOR: 'PROVEEDOR',
  SUELDO: 'SUELDO',
  VARIOS: 'VARIOS',
};

export const ENUM_CONDICION_FISCAL = {
  BLANCO: 'BLANCO',
  EFECTIVO_BLANCO: 'EFECTIVO_BLANCO',
  EFECTIVO_NEGRO: 'EFECTIVO_NEGRO',
};

export const ENUM_ROL = {
  CAJERO: 'CAJERO',
  GERENTE: 'GERENTE',
  ADMIN: 'ADMIN',
};
